#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Determine OS
if [ -f /usr/bin/apt ]; then # Ubuntu
  apt-get install --no-install-recommends -y acl
fi
if [ -f /sbin/apk ]; then # Alpine Linux
  apk add --no-cache acl
fi
chown -R root:root /root
