#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Determine OS
if [ -f /usr/bin/apt ]; then # Ubuntu
  apt-get install --no-install-recommends -y acl
fi
if [ -f /sbin/apk ]; then # Alpine Linux
  apk add --no-cache acl
fi
chown -R root:root /root

# Copy chown function into system wise shell startup folder
CHOWN_PATH=$(which chown)
mv "${CHOWN_PATH}" "${CHOWN_PATH}-noshim"
mv "/defaults/chown-shim.sh" "${CHOWN_PATH}"
chmod +x "${CHOWN_PATH}"
